projects/Intel-OfficePlatform/application/__init__.py
from flask import Flask
from application.index.views import indexPage
from application.exporter.views import exporterPage
from application.importer.views import importerPage


def create_app():
    app = Flask(__name__)

    register_blueprints(app)

    return app


def register_blueprints(app):
    app.register_blueprint(indexPage)
    app.register_blueprint(exporterPage)
    app.register_blueprint(importerPage)

    pass

projects/Intel-OfficePlatform/application/exporter/views.py
from flask import Blueprint, render_template, send_file
from application.exporter.logic import generate_excel

import os


exporterPage = Blueprint('exporterPage', __name__)


@exporterPage.route("/expoter")
def exporter():
    return render_template('expoter.html')


@exporterPage.route("/expoter/ckmx")
def export_ckmx():
    generate_excel(tableName='ckmx', documentName='出库明细')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '出库明细.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/cpmx")
def export_cpmx():
    generate_excel(tableName='cpmx', documentName='产品明细')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '产品明细.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/ddmx")
def export_ddmx():
    generate_excel(tableName='ddmx', documentName='订单明细')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '订单明细.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/htmx")
def export_htmx():
    generate_excel(tableName='htmx', documentName='合同明细')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '合同明细.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/zpsr")
def export_zpsr():
    generate_excel(tableName='zpsr', documentName='装配收入')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '装配收入.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/yflr")
def export_yflr():
    generate_excel(tableName='yflr', documentName='研发利润')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '研发利润.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/hccb")
def export_hccb():
    generate_excel(tableName='hccb', documentName='耗材成本')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '耗材成本.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/lrtz")
def export_lrtz():
    generate_excel(tableName='lrtz', documentName='利润调整')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '利润调整.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/fpsr")
def export_fpsr():
    generate_excel(tableName='fpsr', documentName='分配收入')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '分配收入.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/lrmx")
def export_lrmx():
    generate_excel(tableName='lrmx', documentName='利润明细')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '利润明细.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/lrhz")
def export_lrhz():
    generate_excel(tableName='lrhz', documentName='利润汇总')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '利润汇总.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/hthklr")
def export_hthklr():
    generate_excel(tableName='hthklr', documentName='合同回款利润')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '合同回款利润.xlsx'), as_attachment=True)


@exporterPage.route("/expoter/tzclcb")
def export_tzclcb():
    generate_excel(tableName='tzclcb', documentName='调整材料成本')

    return send_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '调整材料成本.xlsx'), as_attachment=True)

projects/Intel-OfficePlatform/application/importer/views.py
from flask import Blueprint, render_template


importerPage = Blueprint('importerPage', __name__)


@importerPage.route('/importer')
def importer():
    return render_template('importer.html')

projects/Intel-OfficePlatform/application/index/views.py
from flask import Blueprint, render_template


indexPage = Blueprint("indexPage", __name__)


@indexPage.route("/")
def index():
    return render_template('index.html')

projects/Intel-OfficePlatform/application/templates/expoter.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png" sizes="32x32">
    <!-- All CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css') }}">
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
</head>
<body>
    <main class="main-content-area">
        <div class="job-categories-area bg-color2 pt-100 pb-100 clearfix">
            <div class="container">
                <div class="cat-list-items">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_ckmx') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_01.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            出库明细
                                            <span>热力经营报表出库明细</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_cpmx') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_02.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            产品明细
                                            <span>热力经营报表产品明细</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_ddmx') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_03.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            订单明细
                                            <span>热力经营报表订单明细</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_htmx') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_04.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            合同明细
                                            <span>热力经营报表合同明细</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_zpsr') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_05.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            装配收入
                                            <span>热力经营报表装配收入</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_yflr') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_06.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            研发利润
                                            <span>热力经营报表研发利润</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_hccb') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_07.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            耗材成本
                                            <span>热力经营报表耗材成本</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_lrtz') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_08.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            利润调整
                                            <span>热力经营报表利润调整</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_fpsr') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_09.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            分配收入
                                            <span>热力经营报表分配收入</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_lrmx') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_10.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            利润明细
                                            <span>热力经营报表利润明细</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_lrhz') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_11.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            利润汇总
                                            <span>热力经营报表利润汇总</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_hthklr') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_12.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            合同回款利润统计
                                            <span>热力经营报表合同回款利润统计</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.export_tzclcb') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/report_13.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            调整材料成本
                                            <span>热力经营报表调整材料成本</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <footer>
        <div class="footer-bottom-area clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer-bottom text-center">
                            <p>Copyright &copy; 2025.Powered By 王志强.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </footer>

    <div class="preloader" id="preloader">
        <div class="lds-ripple">
            <div></div>
            <div></div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/modules/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/magnific.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/slimmenu.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

projects/Intel-OfficePlatform/application/templates/importer.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png" sizes="32x32">
    <!-- All CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css') }}">
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
</head>
<body>
    <main class="main-content-area content">
        <div class="about-content-area pb-100 pt-100 clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-12 align-items-center themeix-high">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="call-back themeix-high">
                                    <form action="#" data-aos="fade-up">
                                        <p>
                                            <span class="title">二网设备导入模板生成程序</span>
                                        </p>
                                        <p>
                                            <input type="text" placeholder="流程名称" />
                                            <input class="mt-2 buttonfx curtainup" type="file" value="打开" />
                                        </p>
                                        <p><button type="button" class="mt-2 buttonfx curtainup">打开</button></p>
                                        <p><input type="text" placeholder="流程版本" /></p>
                                        <button type="submit" class="mt-2 buttonfx curtainup">升级</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{#    <footer>#}
{#        <div class="footer-bottom-area">#}
{#            <p>Copyright &copy; 2025.Powered By 王志强.</p>#}
{#        </div>#}
{#    </footer>#}

    <script src="{{ url_for('static', filename='js/modules/jquery-3.4.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/proper.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/jquery.waypoints.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/owl.carousel.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/magnific.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/typing.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/select2.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/aos.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/modules/slimmenu.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

projects/Intel-OfficePlatform/application/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png" sizes="32x32">
    <!-- All CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css') }}">
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
</head>
<body>
    <main class="main-content-area">
        <div class="job-categories-area bg-color2 pt-100 pb-100 clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-title text-left">
                            <span>天翔</span>
                            <h2>综合办公平台</h2>
                            <div class="line"></div>
                        </div>
                    </div>
                </div>
                <div class="cat-list-items">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/updater.jpg') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            业务流程升级
                                            <span>免停办实时升级业务链流程</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('importerPage.importer') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/importer.jpg') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            二网设备文件
                                            <span>格式化生成二网设备导入文件</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="{{ url_for('exporterPage.exporter') }}" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/exporter.jpg') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            报表文件导出
                                            <span>格式化导出各类报表 Excel 文件</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/question.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            开发中……
                                            <span>待完善……</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/question.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            开发中……
                                            <span>待完善……</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/question.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            开发中……
                                            <span>待完善……</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/question.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            开发中……
                                            <span>待完善……</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/question.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            开发中……
                                            <span>待完善……</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-4">
                            <a href="https://www.baidu.com" target="_blank">
                                <div class="single-category text-center" data-aos="flip-up">
                                    <div class="cat-icon">
                                        <img src="{{ url_for('static', filename='images/question.png') }}" alt="image" />
                                    </div>
                                    <div class="cat-details">
                                        <h4>
                                            开发中……
                                            <span>待完善……</span>
                                        </h4>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <footer>
        <div class="footer-bottom-area clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer-bottom text-center">
                            <p>Copyright &copy; 2025.Powered By 王志强.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </footer>

    <div class="preloader" id="preloader">
        <div class="lds-ripple">
            <div></div>
            <div></div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/modules/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/magnific.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modules/slimmenu.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>